name: CheeseEssentials
author: cheesepro
version: 1
description: Core plugin for MineFuture
main: me.cheesepro.ce.mainpack.CEMain
commands:
  gmc:
    description: Gamemode Creative
    permission: CheeseEss.gmc
    permission-message: §4§lYou don't have Permission!!
  gms:
    description: Gamemode Survival
    permission: CheeseEss.gms
    permission-message: §4§lYou don't have Permission!!
  heal:
    description: Heal yourself or others
    permission: CheeseEss.heal
    permission-message: §4§lYou don't have Permission!!
  feed:
    description: Feed yourself or others
    permission: CheeseEss.feed
    permission-message: §4§lYou don't have Permission!!
  fly:
    description: Enable/Disable flying ability
    permission: CheeseEss.fly
    permission-message: §4§lYou don't have Permission!!
  speed:
    description: Set flying/walking speed
    permission: CheeseEss.speed
    permission-message: §4§lYou don't have Permission!!
  adminchat:
    description: Enable/Disable Adminchat
    permission: CheeseEss.adminchat
    permission-message: §4§lYou don't have Permission!!
  tp:
    description: Teleport players
    permission: CheeseEss.tp
    permission-message: §4§lYou don't have Permission!!
  tpall:
    description: Teleport all players
    permission: CheeseEss.tpall
    permission-message: §4§lYou don't have Permission!!
  back:
    description: Teleport to your last location
    permission: CheeseEss.back
    permission-message: §4§lYou don't have Permission!!
  logoutloc:
      description: Teleport to your logout location
      permission: CheeseEss.logoutloc
      permission-message: §4§lYou don't have Permission!!
  jump:
      description: Teleport to your eye pointing location
      permission: CheeseEss.jump
      permission-message: §4§lYou don't have Permission!!
  hat:
      description: Get yourself a custom hat
      permission: CheeseEss.hat
      permission-message: §4§lYou don't have Permission!!
  invsee:
      description: Open other player's Inventory
      permission: CheeseEss.invsee
      permission-message: §4§lYou don't have Permission!!
  tpa:
      description: Send a teleport request
      permission: CheeseEss.tpa
      permission-message: §4§lYou don't have Permission!!
  tpaccept:
      description: Accept a teleport request
      permission: CheeseEss.tpaccept
      permission-message: §4§lYou don't have Permission!!
  tpdeny:
      description: Deny a teleport request
      permission: CheeseEss.tpdeny
      permission-message: §4§lYou don't have Permission!!
  sudo:
      description: Force a player to preform a command or message
      permission: super.sudo
      permission-message: §4§lYou don't have Permission!!
  barmsg:
      description: Sets the message of the boss bar
      permission: CheeseEss.barmsg
      permission-message: §4§lYou don't have Permission!!
  workbench:
      description: Open your/other a workbench
      permission: CheeseEss.workbench
      permission-message: §4§lYou don't have Permission!!
  clear:
      description: Clears inventory
      permission: CheeseEss.clear
      permission-message: §4§lYou don't have Permission!!
  clear:
      description: Clears inventory
      permission: CheeseEss.clear
      permission-message: §4§lYou don't have Permission!!
  warplist:
      description: Displays all the warps
      permission: CheeseEss.warplist
      permission-message: §4§lYou don't have Permission!!
  warp:
      description: Warp to a location
      permission: CheeseEss.warp
      permission-message: §4§lYou don't have Permission!!
  setwarp:
      description: Set a warp location
      permission: CheeseEss.setwarp
      permission-message: §4§lYou don't have Permission!!
  delwarp:
      description: Delete a warp location
      permission: CheeseEss.delwarp
      permission-message: §4§lYou don't have Permission!!
  spawn:
      description: Teleport to spawn
      permission: CheeseEss.spawn
      permission-message: §4§lYou don't have Permission!!
  setspawn:
      description: Set the spawn location
      permission: CheeseEss.setspawn
      permission-message: §4§lYou don't have Permission!!
  delspawn:
      description: Delete the spawn location
      permission: CheeseEss.delspawn
      permission-message: §4§lYou don't have Permission!!
  sysinfo:
      description: Show System informations
      permission: CheeseEss.sysinfo
      permission-message: §4§lYou don't have Permission!!
  homelist:
      description: Displays all the homes
      permission: CheeseEss.homelist
      permission-message: §4§lYou don't have Permission!!
  home:
      description: Teleport to home location
      permission: CheeseEss.home
      permission-message: §4§lYou don't have Permission!!
  sethome:
      description: Set a home location
      permission: CheeseEss.sethome
      permission-message: §4§lYou don't have Permission!!
  delhome:
      description: Delete a home location
      permission: CheeseEss.delhome
      permission-message: §4§lYou don't have Permission!!
  hub:
      description: Teleport to hub location
      permission: CheeseEss.hub
      permission-message: §4§lYou don't have Permission!!
  sethub:
      description: Set the hub location
      permission: CheeseEss.sethub
      permission-message: §4§lYou don't have Permission!!
  delhub:
      description: Delete the hub location
      permission: CheeseEss.delhub
      permission-message: §4§lYou don't have Permission!!
  slap:
      description: Slap someone
      permission: CheeseEss.slap
      permission-message: §4§lYou don't have Permission!!
  rocket:
      description: Rocket someone
      permission: CheeseEss.rocket
      permission-message: §4§lYou don't have Permission!!
  lightning:
      description: Lightning strike someone
      permission: CheeseEss.lightning
      permission-message: §4§lYou don't have Permission!!
  tell:
      description: Send a private message to someone
      permission: CheeseEss.tell
      permission-message: §4§lYou don't have Permission!!
  msg:
      description: Send a private message to someone
      permission: CheeseEss.tell
      permission-message: §4§lYou don't have Permission!!
  mute:
      description: Mute a player
      permission: CheeseEss.mute
      permission-message: §4§lYou don't have Permission!!
  unmute:
      description: Unmute a player
      permission: CheeseEss.unmute
      permission-message: §4§lYou don't have Permission!!
  kill:
      description: Kill a player
      permission: CheeseEss.kill
      permission-message: §4§lYou don't have Permission!!
  spam:
      description: Spam the chat
      permission: CheeseEss.spam
      permission-message: §4§lYou don't have Permission!!
  broadcast:
      description: Broadcast a message
      permission: CheeseEss.broadcast
      permission-message: §4§lYou don't have Permission!!
  cchat:
      description: Clears the chat
      permission: CheeseEss.cchat
      permission-message: §4§lYou don't have Permission!!
  vanish:
      description: Vanish yourself
      permission: CheeseEss.vanish
      permission-message: §4§lYou don't have Permission!!
      
permissions:
  CheeseEss.gmc:
    default: op
  CheeseEss.gms:
    default: op
  CheeseEss.heal:
    default: op
  CheeseEss.feed:
    default: op
  CheeseEss.fly:
    default: op
  CheeseEss.adminchat:
    default: op
  CheeseEss.tp:
    default: op
  CheeseEss.tpall:
    default: op
  CheeseEss.back:
    default: true
  CheeseEss.logoutloc:
    default: true
  CheeseEss.speed:
    default: op
  CheeseEss.jump:
    default: op
  CheeseEss.hat:
    default: op
  CheeseEss.invsee:
    default: op
  CheeseEss.tpa:
    default: true
  CheeseEss.tpaccept:
    default: true
  CheeseEss.tpdeny:
    default: true
  CheeseEss.barmsg:
    default: op
  CheeseEss.workbench:
    default: op
  CheeseEss.clear:
    default: true
  CheeseEss.clear.other:
    default: op
  CheeseEss.warplist:
    default: true
  CheeseEss.warp:
    default: true
  CheeseEss.setwarp:
    default: op
  CheeseEss.delwarp:
    default: op
  CheeseEss.spawn:
    default: true
  CheeseEss.setspawn:
    default: op
  CheeseEss.delspawn:
    default: op
  CheeseEss.sysinfo:
    default: op
  CheeseEss.homelist:
    default: true
  CheeseEss.home:
    default: true
  CheeseEss.sethome:
    default: true
  CheeseEss.delhome:
    default: true
  CheeseEss.homemax.1:
    default: true
  CheeseEss.hub:
    default: true
  CheeseEss.sethub:
    default: op
  CheeseEss.delhub:
    default: op
  CheeseEss.slap:
    default: op
  CheeseEss.rocket:
    default: op
  CheeseEss.lightning:
    default: op
  CheeseEss.tell:
    default: true
  CheeseEss.mute:
    default: op
  CheeseEss.unmute:
    default: op
  CheeseEss.kill:
    default: op
  CheeseEss.spam:
    default: op
  CheeseEss.broadcast:
    default: op
  CheeseEss.cchat:
    default: op
  CheeseEss.vanish:
    default: op
  CheeseEss.vanish.complete:
    default: op


  CheeseEss.chat.color:
    default: op

  CheeseEss.fly.other:
    default: op
  CheeseEss.gm.other:
    default: op

  super.sudo:
    default: op

